name: GitHub Actions Demo
run-name: ${{ github.actor }} pushed. Testing if maven builds 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
          cache-dependency-path: '/pom.xml'
      - name: Build with Maven
      - run: mvn -B package --file pom.xml